version: '3'
services:
  api:
    image: kikoken/climate-frontend
    container_name: climate-frontend
    restart: always
    expose:
    - 3000
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:climatecapital.cloud"
      - "traefik.enable=true"
      - "traefik.port=3000"
    networks:
      - traefik
  
  
networks:
  traefik:
    external: true
