version: "3"

services:
  traefik:
    image: traefik:alpine
    container_name: 'traefik'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
  client:
    image: nginx
    container_name: 'nginx'
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:dev.localhost"
    networks:
      - traefik

networks:
  traefik:
    external: true