version: '3'
services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    command: --docker --docker.domain=climatecapital.io
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - traefik
    labels:
      - "traefik.frontend.rule=Host:climatecapital.io"
      - "traefik.port=8080"
  web:
    image: kikoken/climate-frontend
    container_name: climate-frontend
    ports:
    - "3000:3000"
    labels:
    - traefik.enable=true
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:climatecapital.io"
    - "traefik.docker.network=traefik"
    restart: always
    command: serve -s build -l 3000 
    networks:
    - traefik
    - climate
networks:
  traefik:
    external: true
  climate:
    driver: bridge
