version: "3"

services:
  traefik:
    image: traefik:alpine
    container_name: 'traefik'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
  api:
    image: kikoken/api-climate
    container_name: climate-api
    ports:
      - "8000:8000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.climatecapital.cloud"
    networks:
      - traefik

networks:
  traefik:
    external: true