version: '3'
services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    command: --docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8000:8000
    volumes:
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - traefik
  
networks:
  traefik:
    external: true
