version: '3'
services:
  web:
    image: kikoken/climate-frontend
    container_name: climate-frontend
    ports:
    - "3000:3000"
    restart: always
    networks:
    - climate
networks:
  climate:
    driver: bridge
