defaultEntryPoints = ["http", "https"]

[acme]
  email = "info@climatecapital.cloud"
  storageFile = "/acme.json"
  entryPoint = "https"
  acmeLogging = true
  onDemand = true
  OnHostRule = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
     [entryPoints.https.tls]

[web]
address = ":443"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "climatecapital.cloud"
watch = true
swarmmode = false