version: '3'
services:
  api:
    image: kikoken/api-climate
    container_name: climate-api
    ports:
      - "8000:8000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.climatecapital.cloud"
    networks:
      - traefik
  
  
networks:
  traefik:
    external: true
