version: '3'
services:
  apache:
    image: httpd:alpine
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:apache.climatecapital.cloud"
    networks:
      - traefik
  nginx:
    image: nginx:alpine
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:nginx.climatecapital.cloud"
    networks:
      - traefik
  
networks:
  climate:
    driver: bridge
  traefik:
    external: true
