version: '3'
services:
  api:
    image: kikoken/api-climate
    container_name: climate-api
    restart: always
    labels:
      - "traefik.backend=restapi"
      - "traefik.frontend.rule=Host:api.climatecapital.cloud"
      - "traefik.enable=true"
      - "traefik.port=8000"
    networks:
      - traefik
      - climate
    links:
    - redis
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: cache
    labels:
      - "traefik.enable=false"
    expose:
    - 6379
    restart: always
    networks:
    - climate
  
  
networks:
  climate:
    driver: bridge
  traefik:
    external: true
