version: '3'
services:
  back:
    image: kikoken/api-climate
    container_name: climate-api
    ports:
      - "8000:8000"
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:docker.localhost/api"
      - "traefik.docker.network=traefik"
  
  
networks:
  traefik:
    external: true
